version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: dimos
      MYSQL_DATABASE: EDdatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: dimos
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
